/**
 * Equivalencias de Ionicons (lo que la app usaba y lo que guardan las
 * categorías propias y las huchas en Firestore) con los dibujos de Phosphor.
 *
 * Grosor de cada icono:
 * - Los "-outline" de Ionicons pasan al grosor dos tonos (duotone).
 * - Los rellenos, al relleno (fill).
 * - Los de trazo (LINE_ICONS: flechas, +, X…), siempre al grosor normal
 *   (regular): en dos tonos Phosphor les pone detrás un fondo decorativo (el +
 *   salía con un cuadrado y las flechas como triángulos).
 *
 * Para añadir un icono: su línea aquí (o en EXTRA si se usa directamente por
 * su nombre de Phosphor) y `npm run icons`.
 */

// Nombre de Ionicons sin "-outline" → nombre de Phosphor
const IONICON_TO_PHOSPHOR = {
  'add': 'plus',
  'airplane': 'airplane-tilt',
  'alert-circle': 'warning-circle',
  'american-football': 'football',
  'arrow-back': 'arrow-left',
  'arrow-down': 'arrow-down',
  'arrow-down-circle': 'arrow-circle-down',
  'arrow-forward': 'arrow-right',
  'arrow-up': 'arrow-up',
  'bag': 'shopping-bag',
  'balloon': 'balloon',
  'bandage': 'bandaids',
  'bar-chart': 'chart-bar',
  'barbell': 'barbell',
  'basket': 'basket',
  'basketball': 'basketball',
  'bed': 'bed',
  'beer': 'beer-stein',
  'bicycle': 'bicycle',
  'boat': 'boat',
  'book': 'book-open',
  'briefcase': 'briefcase',
  'brush': 'paint-brush',
  'bus': 'bus',
  'business': 'buildings',
  'cafe': 'coffee',
  'calendar': 'calendar-blank',
  'calendar-clear': 'calendar-blank',
  'camera': 'camera',
  'car': 'car',
  'card': 'credit-card',
  'cart': 'shopping-cart',
  'cash': 'money',
  'chatbubble': 'chat-circle',
  'checkmark': 'check',
  'checkmark-circle': 'check-circle',
  'chevron-back': 'caret-left',
  'chevron-down': 'caret-down',
  'chevron-forward': 'caret-right',
  'chevron-up': 'caret-up',
  'close': 'x',
  'close-circle': 'x-circle',
  'color-palette': 'palette',
  'color-wand': 'magic-wand',
  'compass': 'compass',
  'construct': 'wrench',
  'copy': 'copy',
  'create': 'note-pencil',
  'cut': 'scissors',
  'desktop': 'desktop',
  'diamond': 'diamond',
  'document-text': 'file-text',
  'download': 'download-simple',
  'earth': 'globe-hemisphere-west',
  'ellipsis-horizontal': 'dots-three',
  'exit': 'sign-out',
  'eye': 'eye',
  'eye-off': 'eye-slash',
  'fast-food': 'hamburger',
  'film': 'film-strip',
  'fish': 'fish',
  'fitness': 'heartbeat',
  'flame': 'fire',
  'flower': 'flower',
  'football': 'soccer-ball',
  'game-controller': 'game-controller',
  'gift': 'gift',
  'glasses': 'eyeglasses',
  'globe': 'globe',
  'grid': 'squares-four',
  'hand-left': 'hand',
  'headset': 'headset',
  'heart': 'heart',
  'home': 'house',
  'hourglass': 'hourglass',
  'ice-cream': 'ice-cream',
  'image': 'image',
  'images': 'images',
  'infinite': 'infinity',
  'information-circle': 'info',
  'key': 'key',
  'language': 'translate',
  'laptop': 'laptop',
  'leaf': 'leaf',
  'library': 'books',
  'lock-closed': 'lock',
  'lock-open': 'lock-open',
  'log-out': 'sign-out',
  'mail': 'envelope',
  'mail-open': 'envelope-open',
  'man': 'gender-male',
  'map': 'map-trifold',
  'medal': 'medal',
  'medical': 'first-aid-kit',
  'menu': 'list',
  'mic': 'microphone',
  'moon': 'moon',
  'musical-notes': 'music-notes',
  'notifications': 'bell',
  'notifications-off': 'bell-slash',
  'nutrition': 'carrot',
  'partly-sunny': 'cloud-sun',
  'paw': 'paw-print',
  'pencil': 'pencil-simple',
  'people': 'users',
  'person': 'user',
  'person-remove': 'user-minus',
  'phone-portrait': 'device-mobile',
  'pizza': 'pizza',
  'planet': 'planet',
  'pricetag': 'tag',
  'pricetags': 'tag',
  'pulse': 'pulse',
  'radio': 'radio',
  'reader': 'article',
  'receipt': 'receipt',
  'repeat': 'repeat',
  'restaurant': 'fork-knife',
  'ribbon': 'seal-check',
  'rocket': 'rocket-launch',
  'rose': 'flower-tulip',
  'school': 'graduation-cap',
  'search': 'magnifying-glass',
  'send': 'paper-plane-tilt',
  'settings': 'gear',
  'share-social': 'share-network',
  'shield': 'shield',
  'shield-checkmark': 'shield-check',
  'shirt': 't-shirt',
  'snow': 'snowflake',
  'sparkles': 'sparkle',
  'star': 'star',
  'sunny': 'sun',
  'tablet-portrait': 'device-tablet',
  'tennisball': 'tennis-ball',
  'text': 'text-aa',
  'time': 'clock',
  'train': 'train',
  'trash': 'trash',
  'trending-down': 'trend-down',
  'trending-up': 'trend-up',
  'trophy': 'trophy',
  'tv': 'television',
  'umbrella': 'umbrella',
  'videocam': 'video-camera',
  'wallet': 'wallet',
  'watch': 'watch',
  'water': 'drop',
  'wine': 'wine',
  'woman': 'gender-female',
};

// Iconos de trazo: ni el relleno (una caja con el dibujo recortado) ni los dos
// tonos (con un fondo decorativo) les sientan bien. Van con el trazo normal
const LINE_ICONS = new Set([
  'add', 'arrow-back', 'arrow-down', 'arrow-forward', 'arrow-up', 'checkmark',
  'chevron-back', 'chevron-down', 'chevron-forward', 'chevron-up', 'close',
  'ellipsis-horizontal', 'infinite', 'menu', 'repeat', 'search',
  'trending-down', 'trending-up',
]);

// Dibujos de Phosphor que la app usa por su nombre, sin pasar por Ionicons
const EXTRA = [
  'piggy-bank-duotone', 'piggy-bank-fill',
  'clock-counter-clockwise-duotone', 'clock-counter-clockwise-fill',
  'coins-duotone',
];

module.exports = { IONICON_TO_PHOSPHOR, LINE_ICONS, EXTRA };
